#! /bin/sh

# print help message
printHelp() {
    echo "usage tagsistant-tools [-d <command directory>] <command> <arguments>*"
    echo "options:"
    echo -e "\t-d\tconfigure command directory"
    echo "commands:"
    for file in `find $1 -perm -u+x -type f -or -type l`
    do
	fileName=${file##*/}
	message=`grep ^## $file| sed -e 's|^##||g'`
	echo -e "\t${fileName}\t${message}" 
    done
}

# set default command directory
commandDirectory=${HOME}/.tagsistant-command.d/

if [ $# -eq 0 ] 
then
    printHelp ${commandDirectory}
    exit
fi

# get command-name and remove command-name from arguments
if [ $1 = "-d" ]
then
    commandDirectory=$2/
    commandName=$3
    shift 3
else
    commandDirectory=${HOME}/.tagsistant-command.d/
    commandName=$1
    shift 1
fi

if [ ${commandName} = "help" ]
then
    printHelp ${commandDirectory}
    exit
fi

for i in `find ${commandDirectory} -perm -u+x -type f -or -type l`
do
    fileName=${i##*/}
    if [ ${fileName} = ${commandName} ]
    then
	${i} $@
	exit
    fi
done

echo "Invalid command-name:" ${commandName}
printHelp ${commandDirectory}
