#! /bin/sh
## add include relation to tags

if [ $# -lt 2 ] 
then 
     echo "usage include <tag1> <tag2> (tag1 includes tag2)"
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root`

from=$1
to=$2

# create each tag
${directoryName}/mktag ${from} ${to}

mkdir -p ${mountPoint}/relations/${from}/includes/${to}
