#! /bin/sh
## list all files in current tagsistant filesystem

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root`


for file in `find ${mountPoint}/archive -type l -or -type f`
do
  fileName=${file##*/}
  echo `echo ${fileName} | sed -e "s|^(.*)___||g"`
done
