#! /bin/sh
## list all files in current tagsistant filesystem

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root`


for i in `find ${mountPoint}/archive -mindepth 1 -maxdepth 1 -type d`
do
  index=${i##*/}
  for file in `ls ${i}`
  do
    fileName=`echo ${file} | sed -e "s|^${index}___||g"`
    echo ${fileName}
  done
done