#! /bin/sh
## rename file

if [ $# -lt 2 ] 
then 
     echo "usage rename <file> <name>"
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root $1`

if [ $? -ne 0 ]; then
    echo "invalid mountpoint"
    exit 1
fi

# get files to remove
file=$1
name=$2

path=${file%/*}

mv ${file} ${path}/${name}
