#! /bin/sh
## remove file from tagsistant
 
if [ $# -eq 0 ] 
then 
     echo "usage rm <file>*"
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root`

# get files to remove
files=$@

for file in ${files}
do
    query=""
    fileName=${file##*/}
    for tag in `${directoryName}/tags ${file}`
    do
        # process triple tags
        if echo "${tag}" | grep -qE ":.*="; then
            tag=`echo "${tag}" | sed 's/:/:\//; s/=/\/eq\//'`  
        fi
	    query="${query}/${tag}"
    done
    rm ${mountPoint}store/${query}/@/${fileName} -r
done
