#! /bin/sh
## if this script is called with a file path in its first argument, get the tagsistant mount point of that file
## if this script is called without arguments, print mount point of the current directory

tagsistantMountPoints=`df | grep "^tagsistant" | awk '{print $6}'`

if [ -e "$1" ] || [ -L "$1" ]; then
	targetPath=`realpath "$(dirname "$1")"`
else
	targetPath=`realpath "$(pwd)"`
fi

for i in ${tagsistantMountPoints}
do 
    if [[ "$targetPath" == "${i}"* ]]; then 
	    echo "$i"
	    exit 0
    fi
done

echo not mounted by tagsistant
exit 1
