#! /bin/sh
## add tags to files

if [ $# -lt 3 ] 
then 
     echo "usage tag <file>* _ <tag>*"
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root $1`

if [ $? -ne 0 ]; then
    echo "invalid mountpoint"
    exit 1
fi

# get file and tag
files=""
tags=""
isTag=0
tagPath=""
for i in $@
do
    if [ ${isTag} -eq 0 ]
    then 
	if [ $i = "_" ]
	then
	    isTag=1
	else
	    files="${files} $i"
	fi
    else
	tags="${tags} $i"
	tagPath="${tagPath}/$i"
    fi
done

# create each tag
${directoryName}/mktag $tags
# copy files
for file in ${files}
do
    fileName=${file##*/}
    absPath=`readlink -f ${file}`
    case ${absPath} in
	${mountPoint}*)
	    cp ${absPath} ${mountPoint}/store${tagPath}/@/${fileName} -r
	    ;;
	*)
	    ln -s ${absPath} ${mountPoint}/store${tagPath}/@/${fileName}
	    ;;
    esac
done
