#! /bin/sh
## show tags 

if [ $# -eq 0 ] 
then 
     echo "usage tags <file>" 
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root $1`

if [ $? -ne 0 ]; then
    echo "invalid mountpoint"
    exit 1
fi

# get file
file=$1

cat ${file}.tags
