#! /bin/sh
## remove tags from files

if [ $# -lt 3 ] 
then 
     echo "usage untag <file>* - <tag>*"
     exit
fi

# get mount point
directoryName=`dirname $0`
mountPoint=`${directoryName}/root`

# get file and tag
files=""
tags=""
isTag=0
tagPath=""
for i in $@
do
    if [ ${isTag} -eq 0 ]
    then 
	if [ $i = "-" ]
	then
	    isTag=1
	else
	    files="${files} $i"
	fi
    else
	tags="${tags} $i"
	tagPath="${tagPath}/$i"
    fi
done

# copy files
for file in ${files}
do
    fileName=${file##*/}
    rm ${mountPoint}/store${tagPath}/@/${fileName}
done
